/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function encryptEnv(envContent: string, password: string): string
export declare function decryptEnv(encryptedContent: string, password: string): string
